# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-03 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postpage',
            name='category',
            field=models.CharField(choices=[('LAB', 'labor'), ('CAR', 'cars'), ('TRU', 'trucks'), ('WRI', 'writing')], default='zzz', max_length=255),
            preserve_default=False,
        ),
    ]
