# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-08 10:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='urls',
            old_name='pub_date',
            new_name='create_date',
        ),
        migrations.RenameField(
            model_name='urls',
            old_name='count',
            new_name='views_total',
        ),
        migrations.RemoveField(
            model_name='urls',
            name='httpurl',
        ),
        migrations.AddField(
            model_name='urls',
            name='original_url',
            field=models.URLField(default='http://www.nikolad.com', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='urls',
            name='private_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='urls',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='urls',
            name='tracking_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='urls',
            name='views_bot',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='urls',
            name='views_mobile',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='urls',
            name='views_pc',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='urls',
            name='views_tablet',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='urls',
            name='views_touch_capable',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='urls',
            name='short_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='accessdetails',
            name='short_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shortener.Urls'),
        ),
    ]
